version: "3.7"
services:
  proxy:
    image: samply/beam-proxy:develop
    ports:
      - 8081:8081
    environment:
      BROKER_URL: ${BROKER_URL}
      PROXY_ID: ${PROXY_ID}
      APP_${APP_ID_SHORT}_KEY: ${APP_KEY}
      PRIVKEY_FILE: /run/secrets/proxy.pem
      TLS_CA_CERTIFICATE_DIR: ${TLS_CA_CERTIFICATE_DIR}
      NO_PROXY: ${NO_PROXY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      ROOTCERT_FILE: /run/secrets/root.crt.pem
      RUST_LOG: ${RUST_LOG}
    secrets:
      - proxy.pem
      - root.crt.pem
  orchestrator:
    depends_on: [ proxy ]
    build: .
    image: bk-orchestrator:local
    environment:
      BEAM_PROXY_URL: http://proxy:8081
      BEAM_APP_ID: ${APP_ID_SHORT}.${PROXY_ID}
      BEAM_API_KEY: ${APP_KEY}
      TLS_CA_CERTIFICATE_DIR: ${TLS_CA_CERTIFICATE_DIR}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: proxy
      no_proxy: proxy
      RUST_LOG: debug
      RUST_BACKTRACE: "full"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
secrets:
  proxy.pem:
    file: ./pki/${PROXY_ID_SHORT}.priv.pem
  root.crt.pem:
    file: ./pki/root.crt.pem
